name:                task1
version:             0.1.0.0
github:              "Roolen/task1"
license:             BSD3
author:              "Artem"
maintainer:          "zhimovskij@yandex.ru"
copyright:           "© Zhimovskij Artem"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Roolen/task1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  task1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - task1

tests:
  task1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - task1
